config/routes.rb
Rails.application.routes.draw do
  resources :bills

  resources :expense_categories do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :groups do
  collection do
    delete 'destroy_multiple_members'
    end
  end

  resources :tags do
  collection do
    delete 'destroy_multiple'
    end
  end

  devise_for :users

  root to: "bills#new"

end

app/models/bill.rb
class Bill < ActiveRecord::Base

  belongs_to :user
  has_many :tags_with_amounts

  validates :description, :total, :user_id, :group_id, presence: true

end

app/models/expense_category.rb
class ExpenseCategory < ActiveRecord::Base
  belongs_to :group
  validates_presence_of :group_id
  validates :description,  :uniqueness => { :scope => :group_id }
  validates_presence_of :description
end

app/models/expensecategory.rb
class Expensecategory < ActiveRecord::Base
  belongs_to :group
  validates_presence_of :group_id
  validates :description,  :uniqueness => { :scope => :group_id }
  validates_presence_of :description
end

app/models/group.rb
class Group < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :bills
  has_many :expense_categories

  validates :group_name,  :uniqueness => { :scope => :owner_id }
  validates :group_name, :owner_id,  presence: true
end

app/models/groups_users.rb
class Groups_users < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/tag.rb
class Tag < ActiveRecord::Base

 belongs_to :user
  validates :description, presence: true
  validates :description,  :uniqueness => { :scope => :user_id }

end

app/models/tags_with_amount.rb
class TagsWithAmount < ActiveRecord::Base
  belongs_to :bill
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login

  has_many :tags
  has_and_belongs_to_many :groups
  has_many :bills
  validates :email,:username, presence: true
  validates :email,:username, uniqueness: true

  validates :username,
            :uniqueness => {
                :case_sensitive => false
            }

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  add_flash_types :error, :another_custom_type
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  before_action :validate_group_belongs_to_user, only: [ :create ]

  def new
    render :new
  end

  def create
    bill = Bill.create(user_id: current_user.id, total: params[:total], description: params[:description], group_id: params[:group_id])

    if params[:tags_with_amount_per_user] != nil
    tags_per_user = params[:tags_with_amount_per_user][0].to_hash

    tags_per_user.each do |user_with_tags|
      user_id = user_with_tags[0]
      tags_with_amount = user_with_tags[1]

      tags_with_amount.each do |tag, amount|
        bill.tags_with_amounts.create(amount: amount, user_to_pay_id: user_id, tag_name: tag)
      end
     end
    end

    render :new
  end

  def index
    render :index
  end

  private

  def validate_group_belongs_to_user
    if !current_user.groups.map(&:id).include? params[:group_id].to_i
      flash[:error] = "Failed to create the bill."
      render :new
      return
    end
  end
end

app/controllers/expense_categories_controller.rb
class ExpenseCategoriesController < ApplicationController

  def new
    render :new
  end

  def create
    @group = Group.where(id: params[:expensecategory][:group_id]).first
    ExpenseCategory.create(description: params[:expensecategory][:description], group_id: params[:expensecategory][:group_id]).valid?
    redirect_to edit_group_path(@group.id)
  end

  def destroy
    @expensecategory = ExpenseCategory.find(params[:id])
    @expensecategory.destroy
    render :new
  end

  def destroy_multiple
    @expensecategory = ExpenseCategory.new
    category_to_destroy = ExpenseCategory.find(params[:categories_ids].split(','))
    category_to_destroy.each do |c|
      if current_user.id == c.group.owner_id
        c.destroy
      end
    end
    render :new
  end

  def index
    render :index
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
    render :new
  end

  def create
    if Group.create(owner_id: current_user.id, group_name: params[:group][:group_name]).valid?
      @group = Group.where(:owner_id => current_user.id,:group_name => params[:group][:group_name]).first
      current_user.groups << @group
      @current_group_count = Group.where(owner_id: current_user.id).count
      redirect_to :action => "index"
    else
      @group = Group.create(owner_id: current_user.id, group_name: params[:group][:group_name])
      redirect_to :action => "index"
    end
  end

  def edit
    @group = Group.find(params[:id])
    render :edit => @group
  end

  def update
    @group = Group.find(params[:id])
    if User.find_by_username(params[:member_username])
      if !@group.users.include?(User.find_by_username(params[:member_username]))
        @group.users << User.find_by_username(params[:member_username])
      end
    end
    render :edit
  end

  def destroy_multiple_members
    @group = Group.find(params[:group_id])
    members_ids = params[:members_ids].split(',')
    members_ids.each do |i|
     member = User.find(i)
     if member != User.find(@group.owner_id)
      @group.users.delete(member)
       end
    end
    render :edit
  end

  def index
    @group = Group.new
    @current_group_count = Group.where(owner_id: current_user.id).count
    render :index
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    @tag = Tag.new
    render :new
  end

  def create
    if Tag.create(user_id: current_user.id, description: params[:tag][:description].to_s.capitalize).valid?
      @tag = Tag.where(:user_id => current_user.id, :description => params[:tag][:description].to_s.capitalize).first
      render :new
    else
      @tag = Tag.create(user_id: current_user.id, description: params[:tag][:description].to_s.capitalize)
      render :action => "new"
    end
  end

  def destroy_multiple
    @tag = Tag.new
    tags_to_destroy = Tag.find(params[:tag_ids].split(','))
    tags_to_destroy.each do |t|
      if current_user.id == t.user_id
        t.destroy
      end
    end
    render :new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/created.html.erb
<p>Bill created.</p>

app/views/bills/index.html.erb
<% current_user.bills.each do |b| %>
  <%= label_tag "Description:"%>  <%= label_tag b.description%></br>

  <%= label_tag "Total:" ,nil%>  <%= label_tag b.total ,nil%></br>

  <%= label_tag "Group:"%>  <%= label_tag Group.find(b.group_id).group_name%></br>

  <%= label_tag "Tags:" ,nil%>
    <% if b.tags == nil %>
    <%= label_tag "None",nil%>
    <% else %>
    <% b.tags.split(',').each do |t|%>
    <%= label_tag "||",nil%>
    <%= label_tag t,nil%>
    <%= label_tag "||",nil%>
    <% end %>
  <% end %>
  </br>
  <%= label_tag "------------------------------------------------------"%></br>
<% end %>

app/views/bills/new.html.erb
<div id='bill_input'>
  <div class='content'>
    <h4>Fill out the form to create a new bill.</h4>
    <%= submit_tag "Add/Remove tags", id: :add_tags, class: 'btn-primary btn' %>

    <%= form_tag(bills_path) do %>
      <div class='jumbotron'>
        <div id='selected_tags_container'></div>
          </br>
          <%= number_field_tag "total"%> <%= label_tag "Total" %>
          </br>
          <%= text_field_tag "description"%> <%= label_tag "Description" %>
          </br>
          <%= hidden_field_tag "group_id", 'default-value'%>
          <%= submit_tag "Submit", class: 'btn-primary btn' %>
      </div>
    <% end %>
  </div>
</div>

<div id="hidden_input_line" hidden="hidden">
  <%= number_field_tag nil, nil, step: 0.01 %>
  <%= collection_select(nil, :user, User.all, :id, :username) %>
  <%= label_tag "no value",nil, class: 'tag'%>
  </br>
</div>

<div id='tags_container' class='tags-container jumbotron'>
  <% current_user.tags.each do |t| %>
    <%= submit_tag t.description, class: 'btn-primary btn tag', tag_id: t.id, default_user_id: current_user.id %>
  <% end %>
  </br>
  <%= submit_tag "Done", class: 'done btn-primary btn'%>
</div>

app/views/groups/edit.html.erb
<div id ='category_input'>
  <%= label_tag @group.group_name+' categories'%>
  <div id='categories_container' class='categories-container jumbotron'>

      <% @group.expense_categories.each do |e| %>
        <%= label_tag e.description,nil, class: 'btn-primary btn select_categories', expensecategory_id: e.id %>
      <% end %>
      </div>
  <%= form_tag destroy_multiple_expense_categories_path, method: :delete do %>
      <%= hidden_field_tag :categories_ids, nil %>
      <%= submit_tag "Delete selected categories", class: 'btn-primary btn delete_all'%>
   <% end %>

  <%= form_for :expensecategory, :url => {:controller => "expense_categories", :action => "create", :method => "post" } do|f| %>
    <%= f.label :description%>
    <%=f.text_field :description%>
    <%= f.hidden_field :group_id, value: @group.id%>
    <%= f.submit "Create Category"%>
  <% end %>
  </br>
  <%= submit_tag "Done", id: :done, class: 'btn-primary btn' %>

</div>

<div id='member_input'>
  <div class='content'>
    <h7>Group Settings</h7>
    <%= label_tag @group.group_name+' members'%>
    <div id='invite_members_container' class='invite_members-container jumbotron'>
      <% @group.users.each do |u| %>
        <% if u.id != @group.owner_id%>
      <%= label_tag u.username,nil, class: 'btn-primary btn select_members', id: u.id %>
          <% end %>
      <% end %>
    </div>
      <%= form_tag destroy_multiple_members_groups_path, method: :delete do %>
        <%= hidden_field_tag :members_ids, nil%>
        <%= hidden_field_tag :group_id, @group.id %>
        <%= submit_tag "Remove selected members", class: 'btn-primary btn delete_members'%>
      <% end %>

    <%=form_tag group_path(@group), :method => :patch do %>
      <%= label_tag "Member name:" %> <%= text_field "member_username", nil,id: @group.id%>
      <%= submit_tag "Invite", class: 'btn-primary btn' %>
    <% end %>
    </br>
    ---------------------------------
    </br>
    <%= submit_tag "Add/Remove categories", id: :add_categories, class: 'btn-primary btn' %>

  </div>
</div>

app/views/groups/index.html.erb
    <div id='group_input'>
      <div class='content'>
        </br></br>
        <% if @current_group_count > 0 %>
          <h5>Edit Groups</h5>
          <%= select_tag "groups_select", options_from_collection_for_select(current_user.groups, "id", "group_name") %>
          <%= link_to "Edit Group", nil, id: nil,class: 'edit_group_button' %>
        <% end%>
        </br></br></br>

        <h5>Create a new group</h5>
        <%= form_for @group, :url => {:controller => "groups", :action => "create", :method => "post" } do|f| %>
          <%= f.label :group_name%>
          <%=f.text_field :group_name%>
          <%= f.submit "Create Group"%>
          <%=label_tag @group.errors.full_messages.first,nil, class: 'error' if @group.errors.any? %>
        <% end %>
      </div>
    </div>

app/views/groups/new.html.erb
<div id='group_input'>
  <div class='content'>
    <h5>Choose the name for your group</h5>


    </div>
</div>

app/views/groups/update.html.erb
<h5>member invited</h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ExpenseDividerApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag %>

    <%= javascript_include_tag "application" %>
  </head>
  <body data-no-turbolink="true">

    <%= render "shared/navbar" %>
    <%= render "shared/menu" %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
            <div id='main-content'>
              <%= yield %>
            </div>
        </div>
      </div><!--/row-->


    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_menu.html.erb
<% if user_signed_in? %>
    <div id="menu">
      <ul>
        <li><%= link_to "Groups", groups_path %></li>
        <li><%= link_to "Show Bills", bills_path %></li>
        <li><%= link_to "Create Bill", root_path %></li>
        <li><%= link_to "Tags", new_tag_path %></li>
        <li><%= link_to "Config", edit_user_registration_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <li><a class="menu-opener" href="#">Menu</a></li>
            <li><%= link_to current_user.username, edit_user_registration_path %></li>
            <%= select_tag "groups_select", options_from_collection_for_select(current_user.groups, "id", "group_name") %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tags/created.html.erb
<p>Tag created.</p>

app/views/tags/new.html.erb
<div id='tags_input'>
  <div class='content'>
    <h5> Tags </h5>
    <div id='user_tags_container' class='user_tags-container jumbotron'>
      <%= form_tag destroy_multiple_tags_path, method: :delete do %>
        <% current_user.tags.each do |t| %>
          <%= label_tag t.description,nil, class: 'btn-primary btn select_tags', tag_id: t.id %>
        <% end %>
        <%= hidden_field_tag :tag_ids, nil %>
    </div>
        <%= submit_tag "Delete selected tags", class: 'btn-primary btn delete_all'%>
      <% end %>

      <%= form_for :tag, :url => {:controller => "tags", :action => "create", :method => "post" } do|f| %>
        <%= f.label :description%>
        <%=f.text_field :description%>
        <%= f.submit "Create Tag"%>
        <%=label_tag @tag.errors.full_messages.first,nil, class: 'error' if @tag.errors.any? %>
    <% end %>
  </div>
</div>